version: '3.9'

x-environment: &environment
  TEST: test_value

services:
  core:
    image: literate-octo-spoon
    environment:
        <<: *environment
    restart: unless-stopped
    ports:
      - 8000:8000